In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [3]:
A.shape

(2, 3)

In [4]:
u+v

array([ 9,  7, -4,  9])

In [5]:
u-v

array([ 3, -3, -2,  1])

In [6]:
6*u

array([ 36,  12, -18,  30])

In [7]:
u.v

AttributeError: 'numpy.ndarray' object has no attribute 'v'

In [8]:
u.dot(v)

51

In [11]:
np.linalg.norm(u)

8.602325267042627

In [10]:
np.norm(u)

AttributeError: module 'numpy' has no attribute 'norm'

In [12]:
A+C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [13]:
A - C.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [17]:
A - C.transpose()

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [18]:
B*A

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [19]:
B**A

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [20]:
np.matmul(B,A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [21]:
np.matmul(B,C)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [22]:
np.matmul(C,B)

array([[ 5, -6],
       [ 9, -8],
       [ 6, -6]])

In [24]:
np.linalg.matrix_power(B,4)

array([[ 1, -4],
       [ 0,  1]])

In [25]:
np.matmul(A,A.transpose())

array([[14, 28],
       [28, 69]])

In [26]:
np.matmul(D.transpose(),D)

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])